### ISSUE TITLE
Prihodko: Bad tests, works for you - do not work in main repo

### ISSUE THREAD

**Issue by siriusdevs** [siriusdevs/oop_7-1_2022#16]
#8 
@kirillsev1
Tests: 4 failed, 4 passed
Check it in [action](https://github.com/siriusdevs/oop_7-1_2022/actions/runs/3431203617) and [branch](https://github.com/siriusdevs/oop_7-1_2022/tree/prihodko) .

**Comment by kirillsev1** [comment]
I fixed the bug and sent a new one pull

**Comment by siriusdevs** [comment]
Fixed with PR #15
