### ISSUE TITLE
He is still here

### ISSUE THREAD

**Issue by siriusdevs** [siriusdevs/oop_7-1_2022#7]
Milestone is provided. You are welcome to suggest solutions and/or workarounds.

**Comment by nazaroviktor2** [comment]
# Attempt to survive until 01/20/2023 No. 1: 
- Getting input data -> **_completed 100%_**
 - data exploration -> **_completed 100%_** 
- ### !FOUND WORKAROUND! ###
- attempt to change look -> **_successfully_**
- trying to hide from @siriusdevs -> **_unsuccessfully_**
- ### !ERROR! ### 
- mission failed, you have been discovered
- ### !END OF BAD WORKAROUND! ###

**Comment by siriusdevs** [comment]
Suggested workarounds:
1) Deceive @nazaroviktor2: let him earn stars by solving back-breaking tasks and then give him extra question for each star he earned.
2) Do this to @Max2288 too. He knows too much :fearful:

**Comment by Max2288** [comment]
I'm afraid

**Comment by Max2288** [comment]
bad content - first warning @Max2288

**Comment by nazaroviktor2** [comment]
I think this will help find a workarounds https://github.com/nazaroviktor2/terminal-game-shooter

**Comment by kirillsev1** [comment]
bad content - first warning @kirillsev1

**Comment by siriusdevs** [comment]
> I think this will help find a workarounds https://github.com/nazaroviktor2/terminal-game-shooter

"..will help **_to_** find..", @nazaroviktor2

**Comment by siriusdevs** [comment]
![photo_5222397481810248586_x](https://user-images.githubusercontent.com/102812997/205986597-27f0531a-9c9b-492a-8774-debde42ca1c4.jpg)

**Comment by nazaroviktor2** [comment]
# FOUND NEW WORKAROUND
 - You have to become a headman to avoid kick.
- trying to become headman -> successful
# @nazaroviktor2 successfully seized power
## 🏆 14 people became parishioners, you know who will be next
@siriusdevs what will you do now?

**Comment by siriusdevs** [comment]
![image](https://user-images.githubusercontent.com/102812997/206025935-29b387a6-7334-4fc0-9c61-919b6c9138e3.png)

**Comment by Max2288** [comment]
bad content - first warning @siriusdevs

**Comment by kirillsev1** [comment]
bad content - second warning @siriusdevs

**Comment by katikovka** [comment]
bad content - third warning @siriusdevs

**Comment by nazaroviktor2** [comment]
**bad content** - fourth warning @siriusdevs

**Comment by siriusdevs** [comment]
Found out that my students are not very much of LOTR fans.
The exam will be furious, worse than ever

**Comment by siriusdevs** [comment]
![73fvuf](https://user-images.githubusercontent.com/102812997/206126650-82fc28b9-555c-4107-8456-a8bcc3632c92.jpg) ..and you?

**Comment by nazaroviktor2** [comment]
![IMG_20221207_113714](https://user-images.githubusercontent.com/45715124/206130770-b4326ea0-4d48-413c-8ce3-8b9e832dbda9.jpg)

-- I never thought I’d die fighting side by side with an elf.
--How about side by side with a friend?
-- Aye. I could do that.

**Comment by Max2288** [comment]
![изображение](https://user-images.githubusercontent.com/42071821/206132198-344e3d9f-8856-4498-859e-bfaa7fbd824a.png)

**Comment by nazaroviktor2** [comment]
> Found out that my students are not very much of LOTR fans. The exam will be furious, worse than ever

Found a new task rewatch the Lord of the Rings before the exam

**Comment by siriusdevs** [comment]
you might have wanted to say "rewatch" :smiley: 
please watch director's cut. and better watch the original with subtitiles

**Comment by nazaroviktor2** [comment]
> you might have wanted to say "rewatch" smiley please watch director's cut. and better watch the original with subtitiles

![image](https://user-images.githubusercontent.com/45715124/206152521-06e641b8-82de-4b1a-bcf6-2a94834866f5.png)
"*thanks  in elvish*"
